### ISSUE TITLE
Can't add body parts to labeling GUI after extracting outlier frames

### ISSUE THREAD

**Issue by Sofia-Neira** [DeepLabCut/napari-deeplabcut#147]
Hi, 

I extracted outlier frames and opened the labeling GUI but now I cannot add a body part when I try to fix a missing label.

I saw another user had the same issue, so I tried to update it using both methods provided in the issue (#2552) and was not successful. When I check what napari I have in the conda environment, it says napari: 0.4.18

Appreciate the help!

**Comment by MMathisLab** [comment]
Hi @Sofia-Neira  ! Thanks for reporting; to clarify, are most points shown? 

If so, sometimes the point can be off the frame- can you check there by zooming around? As all points always get plotted for adjustment

**Comment by Sofia-Neira** [comment]
Thank you for the quick reply! 

Yes, most points are shown. It's just that the machine labels are sometimes (infrequently) missing a body part that is clearly visible.

I tried to look around off frame and did not find the missing points.

**Comment by gminami** [comment]
Hi @Sofia-Neira, @MMathisLab, I bumped into exactly the same issue with DLC 2.3.9,  napari 0.4.18 and napari deeplabcut 0.2.1.7. My version of way around is to hide 'machinelabels' files in a folder and overwrite 'CollectedData' files as if I'm working on the originally extracted frames. However, if I do so, merge data function no longer works and the project iteration always stays zero (i.e., iteration-0 is overwritten, instead of creating iteration-1, 2, 3,...).
Any suggestions are appreciated.

**Comment by gminami** [comment]
Hi @C-Achard , thanks for flagging this issue elsewhere. In my case, cropping was explicitly disabled:
`cropping: false`
However, earlier in the config.yaml it says the following.
```
video_sets:
  Path\to\my\video.avi:
    crop: 0, 1280, 0, 1024
```
Could this setting still have an effect, even though cropping is set to false? Thanks, and apologize for my ignorance in advance!

**Comment by C-Achard** [comment]
Hello @gminami,

Apologies for the late reply; and thanks for describing your workaround.

What you mentioned is very much in line with the kind of confusing file-handling behavior we are trying to clean up in the current refactor of the plugin, e.g. #164.
If this is still relevant / reproducible on your side, it would be very helpful if you could open a dedicated issue for it. In particular, the following details would help a lot:

- Your current DLC / napari / napari-deeplabcut versions, if they changed since
- Whether this happens in standalone napari, the DLC GUI, or both
- The exact folder contents before/after the workaround and what gets loaded/ignored in the plugin

That would make it much easier to identify whether this is a pure plugin issue, a project layout problem, or an interaction with the DLC GUI.
Thanks again, and sorry this got lost earlier.

**Comment by gminami** [comment]
Hi @C-Achard ,

Thank you for the response. Please see my answers to your questions below:

1. Software Versions
My environment has remained consistent:
DLC: 2.3.9
napari: 0.4.18
napari-deeplabcut: 0.2.1.7

2. Observations
The issue (unable to add occluded labels) persists in the DeepLabCut GUI. Per your suggestion, I also tested the standalone napari for the first time, and the same problem occurred. Additionally, I encountered a separate issue in standalone napari, which I managed to resolve with a specific workaround (see below).

3. Folder Contents & Attachments
Please refer to the attached images for the exact folder structure:
- "Content image1": Shows the main folder with machinelabels files hidden; the remaining files are the images for labeling (e.g., imgxxxxx.png).

<img width="790" height="679" alt="Image" src="https://github.com/user-attachments/assets/82e50093-e41a-4a72-a8ee-89c80d917581" />

- "Content image2": Shows the specific contents of the temp folder.

<img width="795" height="684" alt="Image" src="https://github.com/user-attachments/assets/3d1edbe0-0f39-4600-b408-f4f260d19396" />

- The following is links to machinelabels and CollectedData files.
https://drive.google.com/file/d/16LO5rBsx3Fm6JYZPCvh5jmeIs-P_jNSF/view?usp=sharing
https://drive.google.com/file/d/1Dc-U5g7zCotQu7bqUirKU3dZMTLZgYXa/view?usp=sharing


Issue with standalone napari (Label Mismatch)
When loading a folder containing images and machinelabels_xxxx.h5 in napari, the label-to-image alignment is incorrect.
- The Problem: The images follow the file name order (img00001, img00002, etc.), but the machinelabels_xxxx.h5 data is organized differently. For example, labels intended for img00100 are overlaid on img00001.
- Comparison: This issue does not occur when loading a folder with CollectedData_xxxx.h5; in that case, the labels and images match perfectly.
- Workaround: I found that loading the "Keypoint controls" plugin prior to loading the folder prevents this mismatch.

Thank you for your support!
Best,
Genki

**Comment by C-Achard** [comment]
Hello @gminami, thank you very much for the detailed follow-up.

Since this also occurs in standalone napari-DLC, it looks like there are two separate issues involved here:

- The original issue of not being able to add a missing keypoint during refinement
  - This has been fixed in the ongoing refactor at #175, which I edited just now thanks to your feedback
- The image/label remapping mismatch issue, which was previously fixed in napari-deeplabcut 0.2.1.8, specifically in #157 

If you would like to test these fixes (and hopefully avoid needing the workaround), you can install the plugin directly from this branch in the same conda environment/venv you use for DeepLabCut:
`pip install --upgrade "git+https://github.com/DeepLabCut/napari-deeplabcut.git@cy/fix-multi-trails-refactor"`
After installing, restart napari / the DLC GUI before testing again.
Please note that this branch is still development code and is not considered fully stable yet, so I would strongly recommend backing up your project/data folder first, just in case (if not done already). This won't affect DLC and the GUI itself, only the napari plugin.

Once you are done testing, you can reinstall your preferred released version with:
`pip install napari-deeplabcut==0.2.1.8` 
(or 0.2.1.7 if preferred, but the latest version should fix the remapping).

If you do try the branch, it would be helpful to know:

- Whether the two issues you listed in your latest message still occur
- Whether opening the Keypoint controls first still changes the behavior (this should be fixed as well)

Hope this helps, and thanks again for your report.

Best,
Cyril

**Comment by gminami** [comment]
Hi @C-Achard ,

Thank you for your continued support. And sorry for somewhat belated response.

To be direct: the patch has moved us one step forward, but several issues remain. Because the fix requires Python 3.10+, I had to set up a new environment. This resulted in the following version changes:
- DLC: 2.3.9 (unchanged)
- napari: 0.4.18 → 0.6.6
- napari-deeplabcut: 0.2.1.7 → 0.2.1.9.dev160+g47bdbbf0a
- Python: 3.9 → 3.10

Due to various incompatibilities during installation, I am currently "Analyzing videos" and "Extracting outlier frames" in my old environment, while using the new environment only for the Labeling GUI.

**The Good News:**
The patch fixed the primary issue; I can now add occluded body parts when launching napari from the DLC GUI.

**Remaining Issues:**
Point Size (minor): I am unable to change the point size. I believe this is likely not the issue inherent to your patch but potentially due to incompatibility of some component versions, such as NumPy.
Overwriting Layers (minor): Overwriting an existing layer fails and corrupts the labeling. My current workaround is to delete the existing CollectData files before saving.
Merging Data: The "Merge Data" step fails in both environments. Clicking the button triggers a message saying "you need to proceed to create dataset." I attempted this, but it simply recreated the old dataset with a new timestamp rather than merging the new labels.

The last issue makes me stuck again; although I'm not able to tell if this is or is not outside of the scope of the original problem.
Does the fact that I saved my CollectData files under different names (i.e., "scorer" has changed) from the original dataset affect the merge process?
Also, is it normal to have "likelihood" columns in CollectedData files? It didn't exist in the CollectedData files for originally annotated data.

Best,
Genki

**Comment by C-Achard** [comment]
Hello @gminami, thanks for the follow-up, and sorry for the continued trouble.

**Before reading everything below, I do think the easiest at this point would be to share some of your data, I'm happy to try and reproduce the issues you encounter locally.**

There are quite a few simultaneous issues and to really narrow things down, having at least part of your project (config.yaml, one or two problematic labeled-data folder(s) with all files, and ideally the matching source video(s) as well) would be very helpful. 
Sharing models or other projects outputs would be optional here. I also understand videos may be private, a clipped version would be fine.

Otherwise I will try to address as much as I can below to help you proceed, please let me know if anything is unclear!

---

### Merge data failure

Regarding your current blocker, having mismatched scorer names across config/h5/csv will definitely cause issues with merging.
The best I can recommend is:

- **In a new, fresh backup of your project:**
- Decide what the scorer name should be
  - Ensure it is set in config.yaml
  - Check the csv file(s) and if the scorer name is wrong, search and replace it 
  - Re-generate the h5 using `convertcsv2h5(config_path, scorer='<new_scorer_name>')`
- Check that all the labeled folders have a corresponding video in config.yaml (`video_sets`)
- To get more informative errors, try running commands directly in a script/ipython rather than the GUI:
```python
import deeplabcut
config_path = r"C:\path\to\config.yaml"
deeplabcut.convertcsv2h5(config_path, scorer="YourTargetScorer")
deeplabcut.create_training_dataset(config_path)
```

---
#### Likelihood column
Regarding the likelihood columns, if this is a single-animal project, then CollectedData is normally expected to contain only x and y coordinates (with scorer / bodyparts / coords headers). I would try the above steps first, but if this causes issues you can remove it in regular CollectedData files using :
```python
import pandas as pd
from pathlib import Path

project_folder = Path("C:\path\to\your\project")
target_scorer = "UpdatedScorer"

for h5_path in project_folder.glob(f"labeled-data/*/CollectedData_{target_scorer}.h5"):
    df = pd.read_hdf(h5_path, key="df_with_missing")
    keep = df.columns.get_level_values(-1).isin(["x", "y"])
    df_xy = df.loc[:, keep]
    df_xy.to_hdf(h5_path, key="df_with_missing", mode="w")
    csv_path = h5_path.with_suffix(".csv")
    df_xy.to_csv(csv_path)
    print("Cleaned:", h5_path)
```

### Libraries

Since you now have two separate environments (which is perfect here), would it be possible for you to install the latest DLC version (3.0.0rc14) using `pip install --upgrade --pre deeplabcut[gui, tf]` ?
I understand you may need/prefer to stay on 2.3.9 for TF, but since rc14 is the currently actively maintained version, it would help me locate potential bugs, e.g. in dataset merging.
(GPU support is still available for TF on 3.10 on Windows)
Resolving any conflicts would also help determine what is an actual bug vs what is only due to mismatched dependencies; if you can provide either which conflicts occur and/or try installing the latest that would be very helpful. 
~~I will check on my side whether I can get a clean env with both 2.3.9 + the plugin refactor and share relevant commands to help with that part.~~ I have tried to install 2.3.9 + the dev branch of the plugin, it seems the main conflict is with opencv-python/imgaug. Is this what you observed as well ?

### Point size

I assume this is a problem with the dotsize parameter in config.yaml ? Otherwise not being able to set point size in napari might be because you have to select the points you'd like to resize first, I can update how the refactored version handles this if needed, a global control may be more helpful for DLC indeed.

### Overwriting layers

An overwrite warning on save to an existing h5 was indeed added in the refactor, is this what is failing ? 
Here it might be either that the format the plugin is saving in is not compatible with 2.3.9, which would be unexpected, or, due to the scorer mismatch between the h5 and config.yaml, it gets routed incorrectly.
Could you provide the exact steps you follow in the plugin ? Sharing the corrupted h5 would also help a lot in figuring out what could be causing this, as it would let me know exactly what is being corrupted and how.

---

Sorry for the long post, I hope this is useful. Definitely if you could share some of your data, I'm happy to try and reproduce the issues you encounter, and provide more actionable fixes/workarounds. Thanks !

**Comment by gminami** [comment]
Hi @C-Achard 

Thank you for your prompt and helpful response.

I’m still working through your full email, but I wanted to let you know that I made a big dent in the data merge. It’s working now that I’ve aligned the scorer names and dropped the likelihood columns. Fixing the names by itself actually threw a table size error, so both steps were key.

Your advice was spot on. That said, I’m a bit puzzled by the napari interface; it prompted me to name the CollectData file using 'CollectData_human_xxxxx' as an example. Following that suggestion is actually what caused the scorer inconsistency. I would have expected it to default to CollectData_[scorer]. Is this expected behavior in the original setting?

Best,
Genki

**Comment by C-Achard** [comment]
Okay, good to hear !

Thanks for reporting the issue with being asked to name the h5, it sounds like it's not detecting the current scorer in the config properly; I will fix this in the refactor PR.

I've also added an updated way of globally resizing points, which hopefully retains the convenience of the previous versions of the plugin but without overriding napari's GUI (in #182).

Let me know if anything else comes up, and thanks for your patience.

Best,
Cyril
